@extends('frontend.master')

@section('content')
<main class="blog-detail-page">
  <section class="blog-detail-hero"><div class="container"><a href="{{ route('blog.index') }}" class="blog-detail-back"><i class="bi bi-arrow-left"></i> Back to articles</a><div class="blog-detail-category">{{ ucwords(str_replace('-', ' ', $blogPost->category)) }}</div><h1>{{ $blogPost->title }}</h1><p class="blog-detail-lead">{{ $blogPost->excerpt }}</p><div class="blog-detail-meta"><span><i class="bi bi-person-circle"></i> {{ $blogPost->author }}</span><span><i class="bi bi-calendar3"></i> {{ optional($blogPost->published_at)->format('d F Y') ?: 'FlyDayz guide' }}</span><span><i class="bi bi-clock"></i> {{ $blogPost->read_time }}</span></div></div></section>
  <section class="blog-detail-content"><div class="container"><div class="row g-5"><div class="col-lg-8"><article class="blog-article"><img class="blog-detail-cover" src="{{ $blogPost->image_url }}" alt="{{ $blogPost->title }}"><div class="blog-article-copy">{!! nl2br(e($blogPost->content)) !!}</div><div class="blog-article-share"><span>Found this useful?</span><a href="https://wa.me/?text={{ urlencode($blogPost->title . ' ' . route('blog.show', $blogPost)) }}" target="_blank" rel="noopener"><i class="bi bi-whatsapp"></i> Share on WhatsApp</a></div></article></div><aside class="col-lg-4"><div class="blog-detail-aside"><div class="blog-detail-aside-icon"><i class="bi bi-heart-pulse"></i></div><h3>Care, made simpler.</h3><p>Explore guidance that helps you feel more informed and confident every day.</p><a href="{{ route('blog.index') }}" class="blog-read-link">Browse all articles <i class="bi bi-arrow-right"></i></a></div></aside></div></div></section>
  @if($relatedPosts->isNotEmpty()) <section class="blog-related section"><div class="container"><div class="blog-section-head"><div class="blog-kicker"><span><i class="bi bi-bookmark-heart"></i></span> Keep Reading</div><h2>Related Articles</h2></div><div class="blog-card-grid">@foreach($relatedPosts as $post)<article class="blog-card"><div class="blog-card-media"><img src="{{ $post->image_url }}" alt="{{ $post->title }}"><span class="blog-card-category">{{ ucwords(str_replace('-', ' ', $post->category)) }}</span></div><div class="blog-card-body"><div class="blog-card-meta"><span>{{ $post->read_time }}</span><span>{{ $post->author }}</span></div><h3>{{ $post->title }}</h3><p>{{ $post->excerpt }}</p><a href="{{ route('blog.show', $post) }}">Read Article <i class="bi bi-arrow-right"></i></a></div></article>@endforeach</div></div></section> @endif
</main>
@endsection
