@extends('frontend.master')

@section('content')
<main class="products-page">
  <section class="product-page-hero"><div class="product-page-glow one"></div><div class="product-page-glow two"></div><div class="container position-relative"><div class="row align-items-center g-4 g-lg-5"><div class="col-lg-6"><div class="product-page-kicker"><span><i class="bi bi-bag-heart"></i></span>{{ $websiteSettings->website_name }} Premium Products</div><h1 class="product-page-title">Choose Comfort by <span>Flow, Size & Care</span></h1><p class="product-page-text">Explore protection designed around everyday comfort, heavy-flow confidence and peaceful nights.</p><div class="product-hero-actions"><a href="#product-catalog" class="fd-btn-primary">View Products <i class="bi bi-arrow-right-short ms-1"></i></a><a target="_blank" rel="noopener" href="{{ $websiteSettings->whatsappUrl('Hi ' . $websiteSettings->website_name . ' Team, I need help choosing the right product.') }}" class="fd-btn-secondary"><i class="bi bi-whatsapp me-2"></i>Ask on WhatsApp</a></div></div><div class="col-lg-6"><div class="product-hero-visual"><img src="{{ $products->first()?->getFirstMediaUrl('product_main_image') ?: asset('assets/images/products/product2.png') }}" class="product-hero-pack" alt="{{ $websiteSettings->website_name }} product pack"><div class="hero-mini-card a"><i class="bi bi-feather"></i> Soft Touch</div><div class="hero-mini-card b"><i class="bi bi-droplet-fill"></i> Gel Lock</div><div class="hero-mini-card c"><i class="bi bi-shield-check"></i> Leak Guard</div></div></div></div></div></section>

  <section id="product-catalog" class="product-category-section"><div class="container"><div class="category-shell"><div class="category-header"><div><div class="category-kicker"><i class="bi bi-grid-3x3-gap-fill"></i> Category Wise Collection</div><h2 class="category-title">Premium Product Range</h2><p class="category-subtitle">Choose a size or protection type to find the product that suits your comfort needs.</p></div><div class="category-tabs" aria-label="Product filters"><a class="product-filter-btn {{ !request('size') && !request('protection') ? 'active' : '' }}" href="{{ route('products') }}">All</a>@foreach($sizeCategories as $category)<a class="product-filter-btn {{ request('size') === $category->slug ? 'active' : '' }}" href="{{ route('products', ['size' => $category->slug]) }}">{{ $category->name }}</a>@endforeach @foreach($protectionTypes as $type)<a class="product-filter-btn {{ request('protection') === $type->slug ? 'active' : '' }}" href="{{ route('products', ['protection' => $type->slug]) }}">{{ $type->title }}</a>@endforeach</div></div>
        <div class="product-catalog-grid">@forelse($products as $product) @php($image = $product->getFirstMediaUrl('product_main_image') ?: asset('assets/images/products/product.png'))<article class="catalog-card {{ $product->is_featured ? 'featured' : '' }}"><div class="catalog-card-top"><span class="catalog-badge"><i class="bi bi-shield-check"></i> {{ $product->badge_text ?: optional($product->protectionType)->title ?: 'Premium Care' }}</span><span class="catalog-size">{{ $product->size_text ?: optional($product->sizeCategory)->size_label ?: 'Comfort Care' }}</span></div><div class="catalog-media"><img src="{{ $image }}" alt="{{ $product->name }}"></div><div class="catalog-body"><h3>{{ $product->name }}</h3><p>{{ $product->short_description }}</p><div class="catalog-specs"><div class="catalog-spec"><small>Size</small><strong>{{ $product->size_text ?: optional($product->sizeCategory)->name ?: '—' }}</strong></div><div class="catalog-spec"><small>Flow</small><strong>{{ $product->flow_text ?: optional($product->sizeCategory)->flow_label ?: '—' }}</strong></div></div><div class="catalog-actions"><a href="{{ route('products.show', $product->slug) }}" class="catalog-btn primary">View More</a><a target="_blank" rel="noopener" href="{{ $websiteSettings->whatsappUrl('Hi ' . $websiteSettings->website_name . ' Team, I want details about ' . $product->name . '.') }}" class="catalog-btn whatsapp" aria-label="Ask about {{ $product->name }}"><i class="bi bi-whatsapp"></i></a></div></div></article>@empty<div class="product-empty-state"><i class="bi bi-box-seam"></i><h3>No products found</h3><p>Try another category or check back soon.</p><a href="{{ route('products') }}" class="fd-btn-primary">View all products</a></div>@endforelse</div>
        <div class="product-compare-strip"><div><h3>Need help choosing the right {{ $websiteSettings->website_name }} product?</h3><p>Tell us your flow type, usage time and comfort preference. Our team will guide you.</p></div><a target="_blank" rel="noopener" href="{{ $websiteSettings->whatsappUrl('Hi ' . $websiteSettings->website_name . ' Team, please help me choose the right product.') }}" class="fd-btn-primary"><i class="bi bi-whatsapp me-2"></i>Get Guidance</a></div>
      </div></div></section>
</main>
@endsection
