@extends('layouts.admin')

@section('page-title', 'Blog Articles')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Blog Articles</h2><p class="admin-page-subtitle">Create and manage articles shown in the FlyDayz knowledge hub.</p></div><a href="{{ route('admin.blog-posts.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Article</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Articles</p><p class="stat-value">{{ $blogPosts->count() }}</p></div><div class="stat-card"><p class="stat-label">Published</p><p class="stat-value">{{ $blogPosts->where('status', true)->count() }}</p></div><div class="stat-card"><p class="stat-label">Featured</p><p class="stat-value">{{ $blogPosts->where('is_featured', true)->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">All Articles</p></div><div class="page-card-table"><table class="min-w-full datatable datatable-BlogPost"><thead><tr><th></th><th>Article</th><th>Category</th><th>Published</th><th>Status</th><th style="text-align:right;">{{ trans('global.actions') }}</th></tr></thead><tbody>@foreach($blogPosts as $post)<tr data-entry-id="{{ $post->id }}"><td></td><td><p class="table-main-text">{{ $post->title }}</p><p class="table-sub-text">/{{ $post->slug }}</p></td><td><span class="role-tag">{{ ucwords(str_replace('-', ' ', $post->category)) }}</span></td><td style="color:#475569;">{{ optional($post->published_at)->format('d M Y') ?: 'Not scheduled' }}</td><td><span class="role-tag">{{ $post->status ? 'Published' : 'Draft' }}{{ $post->is_featured ? ' · Featured' : '' }}</span></td><td><div class="action-row"><a href="{{ route('blog.show', $post) }}" target="_blank" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.blog-posts.edit', $post) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.blog-posts.destroy', $post) }}" method="POST" style="display:inline" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@csrf @method('DELETE')<button class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts') @parent <script>$(function(){initAdminDataTable('.datatable-BlogPost',{canDelete:true,massDeleteUrl:"{{ route('admin.blog-posts.massDestroy') }}",deleteText:"{{ trans('global.datatables.delete') }}",zeroSelectedText:"{{ trans('global.datatables.zero_selected') }}",confirmText:"{{ trans('global.areYouSure') }}",searchPlaceholder:'Search articles...',infoText:'Showing _START_–_END_ of _TOTAL_ articles'});});</script> @endsection
